# Generated by Django 5.2.8 on 2025-11-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='article',
            field=models.IntegerField(null=True, verbose_name='Артикул'),
        ),
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=10, null=True, verbose_name='код товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.PositiveIntegerField(null=True, verbose_name='Процент скидки'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_with_discount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Цена'),
        ),
    ]
