# Generated by Django 5.2.8 on 2025-11-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_article_product_code_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_with_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена со скидкой'),
        ),
    ]
