# Generated by Django 5.2.8 on 2025-11-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_price_with_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amount',
            field=models.PositiveIntegerField(default=0, verbose_name='количество'),
        ),
    ]
