# Generated by Django 5.2.8 on 2025-11-17 07:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_remove_product_description_productdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdescription',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='Описание'),
        ),
    ]
