# Generated by Django 5.2.8 on 2026-02-18 04:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_product_hit_product_popular_product_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.DeleteModel(
            name='ProductDescription',
        ),
    ]
