# Generated by Django 5.2.8 on 2026-02-20 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_common'),
    ]

    operations = [
        migrations.AddField(
            model_name='common',
            name='add_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='common',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='common',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='common',
            name='work_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('link', models.URLField(blank=True, max_length=255, null=True)),
                ('common', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_networks', to='product.common')),
            ],
        ),
    ]
