# Generated by Django 5.2.8 on 2026-02-27 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_common_add_phone_number_common_address_common_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialnetwork',
            name='common',
        ),
        migrations.DeleteModel(
            name='Common',
        ),
        migrations.DeleteModel(
            name='SocialNetwork',
        ),
    ]
